### ISSUE TITLE
Error:Provision record has no endpoint information specified 

### ISSUE THREAD

**Issue by ashlinsaj** [mattrglobal/osma#32]
When trying to create an invitation on the osma app it shows the error Provision record has no endpoint information specified

**Comment by sukalpomitra** [comment]
@ashlinsaj This is not an issue. This is by design. A mobile edge agent does not have a persistent IP address. The invitation QR code generated will thus have no service endpoint specified. The expectation is that a user, using OSMA will have a cloud agent, that will provide this endpoint.

@tplooker What do you suggest?

**Comment by ashlinsaj** [comment]
The QR code itself is not getting generated.Connection with the web agent is also not happening.
![Screenshot from 2019-09-29 18-06-37(1)](https://user-images.githubusercontent.com/45759808/66181569-ebf5a680-e68e-11e9-8286-10af2d70c57c.png)

**Comment by sukalpomitra** [comment]
hi @ashlinsaj the QR code is not generated where? If in OSMA that's expected. If on agent framework as the screenshot shows then please raise an issue in the agent-framework repo

**Comment by ashlinsaj** [comment]
I am trying to connect through my phone where the osma app is installed.So mobile edge agent can have the ip of the phone.Don't whether what I say make a sense or not.

**Comment by sukalpomitra** [comment]
@ashlinsaj It would help if you follow the Create a Bug template. Give steps to reproduce with screenshots

**Comment by tplooker** [comment]
Hi @ashlinsaj, @sukalpomitra is correct when an OSMA agent is first provisioned it does not have an endpoint for messages to be sent to it, it requires creating a connection with a cloud agent and establishing them as its endpoint for message delivery.

**Comment by naman20sharma** [comment]
> Hi @ashlinsaj, @sukalpomitra is correct when an OSMA agent is first provisioned it does not have an endpoint for messages to be sent to it, it requires creating a connection with a cloud agent and establishing them as its endpoint for message delivery.

Hi @tplooker, I am receiving the same issue as @ashlinsaj was (taking reference from the screenshot above). I wanted to ask the procedure for passing the credentials between the web-agent and Osma Application (edge agent) and how to establish an endpoint for message delivery and further communication between two agents.

**Comment by naman20sharma** [comment]
> > Hi @ashlinsaj, @sukalpomitra is correct when an OSMA agent is first provisioned it does not have an endpoint for messages to be sent to it, it requires creating a connection with a cloud agent and establishing them as its endpoint for message delivery.
> 
> Hi @tplooker, I am receiving the same issue as @ashlinsaj was (taking reference from the screenshot above). I wanted to ask the procedure for passing the credentials between the web-agent and Osma Application (edge agent) and how to establish an endpoint for message delivery and further communication between two agents.

Hi, @tplooker @sukalpomitra  any update with @ashlinsaj  exception ?
