### ISSUE TITLE
Android build is not working

### ISSUE THREAD

**Issue by HarshitaAggrawal** [mattrglobal/osma#33]
I have tried to generate android build on emulator but its showing "Detecting installed packages..." in output window under build. can you please help me out to generate android build on emulator.

**Comment by andrewBSTan** [comment]
Same issue here...follow the steps but unable to build.

**Comment by kdenhartog** [comment]
@tplooker any ideas about what's going on here? I suspect it has something to do with the change from indy to aries in the namespacing.

**Comment by tplooker** [comment]
Hi guys, I have been working on refactoring OSMA over to aries-framework-dotnet, here is the current branch with a build working, I have not tested it with the updated aries-framework samples yet. https://github.com/tplooker/osma/tree/tl/update-to-aries-framework

**Comment by tplooker** [comment]
My intention is to merge this soon, however @sukalpomitra was working upstream of this and I was waiting for his input

**Comment by tplooker** [comment]
@sukalpomitra do you have any update?

**Comment by sukalpomitra** [comment]
@tplooker My version of refactored OSMA is at https://github.com/sukalpomitra/osma/tree/v1.0 and this also depends on some changes on aries-framework-dotnet. I am now testing integration with IIWBOOK and then will do with VCOIDC. You can go ahead and merge your copy. When all my integration passes I will raise a separate PR
