### ISSUE TITLE
Cannot accept invite from newest dotnet agent

### ISSUE THREAD

**Issue by jeffallen** [mattrglobal/osma#34]
Osma currently depends on AgentFramework.Core 4.0.0-preview.662.

When trying to accept an invite from an agent running aries-framework-dotnet commit 5d30511eb829fe the agent fails with "No valid leaving transitions are permitted from state 'Connected' for trigger 'InvitationAccept'."

Updating the dependency to AgentFramework.Core 4.3.0 creates several compile failures I am still working my way through.

More generally: what's the expected state of this project? Is it meant to work with the latest agent release?

**Comment by airoasis** [comment]
Today, I have tested this mobile agent with several different commits, and streetcred-id/agent-framework commit 88d3c87 (20 May, 2019) is the last commit working with this.

**Comment by sukalpomitra** [comment]
@jeffallen can you please check with the current PR merged if this issue still exists? If not, then can you please close the PR

**Comment by jeffallen** [comment]
Sorry, I don't have the whole build environment for this working still. Closing.
