### ISSUE TITLE
OSMA on Windows showing me Bundle of Errors

### ISSUE THREAD

**Issue by x0axz** [mattrglobal/osma#39]
Hi, I'm using windows 10 and trying to install osma but it's giving me a bundle of errors.

I followed the same steps as told to:
**Clone it locally,
Run git lfs pull in order to pull the dependent native libraries with LFS.
Open osma-mobile-app.sln and build!** 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'C:\Users\XEMO\Documents\aries-mobile\osma\src\Osma.Mobile.App\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Osma.Mobile.App	C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
Error	NETSDK1004	Assets file 'C:\Users\XEMO\Documents\aries-mobile\osma\src\Osma.Mobile.App.Services\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Osma.Mobile.App.Services	C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
```

**Error List**
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to download package 'WebSocket4Net.0.15.1' from 'https://api.nuget.org/v3-flatcontainer/websocket4net/0.15.1/websocket4net.0.15.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/websocket4net/0.15.1/websocket4net.0.15.1.nupkg' has timed out after 100000ms.	Osma.Mobile.App.iOS	C:\Users\XEMO\Documents\aries-mobile\osma\src\Osma.Mobile.App.iOS\Osma.Mobile.App.iOS.csproj	1	
Error		Failed to download package 'UXDivers.GorillaPlayer.SDK.1.5.0' from 'https://api.nuget.org/v3-flatcontainer/uxdivers.gorillaplayer.sdk/1.5.0/uxdivers.gorillaplayer.sdk.1.5.0.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/uxdivers.gorillaplayer.sdk/1.5.0/uxdivers.gorillaplayer.sdk.1.5.0.nupkg' has timed out after 100000ms.	Osma.Mobile.App.iOS	C:\Users\XEMO\Documents\aries-mobile\osma\src\Osma.Mobile.App.iOS\Osma.Mobile.App.iOS.csproj	1	
Error		Failed to download package 'System.Threading.Tasks.Extensions.4.4.0' from 'https://api.nuget.org/v3-flatcontainer/system.threading.tasks.extensions/4.4.0/system.threading.tasks.extensions.4.4.0.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.threading.tasks.extensions/4.4.0/system.threading.tasks.extensions.4.4.0.nupkg' has timed out after 100000ms.	Osma.Mobile.App.Android	C:\Users\XEMO\Documents\aries-mobile\osma\src\Osma.Mobile.App.Android\Osma.Mobile.App.Android.csproj	1	
Error		Failed to download package 'Xamarin.Android.Support.v7.MediaRouter.27.0.2.1' from 'https://api.nuget.org/v3-flatcontainer/xamarin.android.support.v7.mediarouter/27.0.2.1/xamarin.android.support.v7.mediarouter.27.0.2.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/xamarin.android.support.v7.mediarouter/27.0.2.1/xamarin.android.support.v7.mediarouter.27.0.2.1.nupkg' has timed out after 100000ms.	Osma.Mobile.App.Android	C:\Users\XEMO\Documents\aries-mobile\osma\src\Osma.Mobile.App.Android\Osma.Mobile.App.Android.csproj	1	
Error		Failed to download package 'System.Reactive.4.1.3' from 'https://api.nuget.org/v3-flatcontainer/system.reactive/4.1.3/system.reactive.4.1.3.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.reactive/4.1.3/system.reactive.4.1.3.nupkg' has timed out after 100000ms.	Osma.Mobile.App.Android	C:\Users\XEMO\Documents\aries-mobile\osma\src\Osma.Mobile.App.Android\Osma.Mobile.App.Android.csproj	1	
Error		Failed to download package 'Microsoft.AppCenter.Analytics.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.appcenter.analytics/2.0.0/microsoft.appcenter.analytics.2.0.0.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.appcenter.analytics/2.0.0/microsoft.appcenter.analytics.2.0.0.nupkg' has timed out after 100000ms.	Osma.Mobile.App.Android	C:\Users\XEMO\Documents\aries-mobile\osma\src\Osma.Mobile.App.Android\Osma.Mobile.App.Android.csproj	1	
`

**Output - Package Manager**
`Failed to download package 'System.Threading.Tasks.Extensions.4.4.0' from 'https://api.nuget.org/v3-flatcontainer/system.threading.tasks.extensions/4.4.0/system.threading.tasks.extensions.4.4.0.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.threading.tasks.extensions/4.4.0/system.threading.tasks.extensions.4.4.0.nupkg' has timed out after 100000ms.
Failed to download package 'Xamarin.FFImageLoading.Transformations.2.4.4.859' from 'https://api.nuget.org/v3-flatcontainer/xamarin.ffimageloading.transformations/2.4.4.859/xamarin.ffimageloading.transformations.2.4.4.859.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/xamarin.ffimageloading.transformations/2.4.4.859/xamarin.ffimageloading.transformations.2.4.4.859.nupkg' has timed out after 100000ms.
Failed to download package 'Acr.UserDialogs.7.0.1' from 'https://api.nuget.org/v3-flatcontainer/acr.userdialogs/7.0.1/acr.userdialogs.7.0.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/acr.userdialogs/7.0.1/acr.userdialogs.7.0.1.nupkg' has timed out after 100000ms.
Failed to download package 'Microsoft.AppCenter.Analytics.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.appcenter.analytics/2.0.0/microsoft.appcenter.analytics.2.0.0.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.appcenter.analytics/2.0.0/microsoft.appcenter.analytics.2.0.0.nupkg' has timed out after 100000ms.
Failed to download package 'Xamarin.Essentials.1.0.0' from 'https://api.nuget.org/v3-flatcontainer/xamarin.essentials/1.0.0/xamarin.essentials.1.0.0.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/xamarin.essentials/1.0.0/xamarin.essentials.1.0.0.nupkg' has timed out after 100000ms.
Failed to download package 'Xamarin.Forms.3.6.0.264807' from 'https://api.nuget.org/v3-flatcontainer/xamarin.forms/3.6.0.264807/xamarin.forms.3.6.0.264807.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/xamarin.forms/3.6.0.264807/xamarin.forms.3.6.0.264807.nupkg' has timed out after 100000ms.
Failed to download package 'Xamarin.Android.Support.v7.MediaRouter.27.0.2.1' from 'https://api.nuget.org/v3-flatcontainer/xamarin.android.support.v7.mediarouter/27.0.2.1/xamarin.android.support.v7.mediarouter.27.0.2.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/xamarin.android.support.v7.mediarouter/27.0.2.1/xamarin.android.support.v7.mediarouter.27.0.2.1.nupkg' has timed out after 100000ms.
Failed to download package 'Xamarin.Android.Support.v4.27.0.2.1' from 'https://api.nuget.org/v3-flatcontainer/xamarin.android.support.v4/27.0.2.1/xamarin.android.support.v4.27.0.2.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/xamarin.android.support.v4/27.0.2.1/xamarin.android.support.v4.27.0.2.1.nupkg' has timed out after 100000ms.
Failed to download package 'Microsoft.AppCenter.Crashes.2.0.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.appcenter.crashes/2.0.0/microsoft.appcenter.crashes.2.0.0.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.appcenter.crashes/2.0.0/microsoft.appcenter.crashes.2.0.0.nupkg' has timed out after 100000ms.
Failed to download package 'Microsoft.Extensions.DependencyInjection.Abstractions.2.1.1' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/2.1.1/microsoft.extensions.dependencyinjection.abstractions.2.1.1.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/2.1.1/microsoft.extensions.dependencyinjection.abstractions.2.1.1.nupkg' has timed out after 100000ms.
`

**Anyone? please help me figure it out.
Regards**

**Comment by kdenhartog** [comment]
We didn't intend to target Windows 10, but Xamarin should be able to support this with tweaks. Unfortunately, we aren't set up to support Windows 10 at this time we'd likely not accept pull requests that add this functionality. Our build goals were to only support Android and iOS for this project. If our intentions change, I'll be sure to let you know.

**Comment by tplooker** [comment]
@x0axz, just checking that your machine had a stable network connection at the time of trying to build this app, as it appears the errors you are getting are due the inability to resolve the nuget packages?

**Comment by tplooker** [comment]
@x0axz to confirm, you can build OSMA from Windows10, but OSMA does not have a Windows10 build target at this stage.

**Comment by kdenhartog** [comment]
> @x0axz to confirm, you can build OSMA from Windows10, but OSMA does not have a Windows10 build target at this stage.

Thanks for the clarification.

**Comment by x0axz** [comment]
@tplooker @kdenhartog . Thanks for ur response. If I can build on Windows 10, then what does these error means? am I missing something.

**Comment by x0axz** [comment]
I think the Issue is that, it can't download Nuget Packages from Agent Framework SDK Nuget (https://www.myget.org/F/agent-framework/api/v3/index.json).

**Comment by x0axz** [comment]
I'm trying to install Nuget Packages from Visual Studio, some of links are NOTFOUND?? Is there anyway I could Install all the missing dependencies?

**Comment by sukalpomitra** [comment]
@x0axz are you using the latest version of osma. 
it should not download anything from agent-framework but from aries-framework-dotnet

**Comment by x0axz** [comment]
i first installed visual studio, then xamarin, and then osma by following these steps: https://github.com/mattrglobal/osma#getting-started
nothing less or more than that and i didn't installed aries-framework-dotnet
the errors are like: nuget, can't download package xyz, becoz of timeout, notfound e.t.c

**Comment by x0axz** [comment]
Trying to install packages through console... still, same old errors

**Input**
`PM> Install-Package Xamarin.Android.Support.Transition -Version 27.0.2.1`

**Error**
```
GET https://www.myget.org/F/agent-framework/api/v3/flatcontainer/zxing.net.mobile/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/zxing.net.mobile/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/zxing.net.mobile/index.json
Install-Package : The feed 'nuget.org [https://api.nuget.org/v3/index.json]' lists package 'ZXing.Net.Mobile.2.4.1' but 
multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the 
current operation was in progress. Verify the package exists on the feed and try again.
  Unable to find package 'ZXing.Net.Mobile.2.4.1'.
At line:1 char:1
+ Install-Package Xamarin.Android.Support.Transition -Version 27.0.2.1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:05:19.8321493`
```

**Comment by x0axz** [comment]
Interesting part is ZXing.Net.Mobile latest version v2.4.1 is already installed.

**Comment by x0axz** [comment]
any update regarding my issue? i spent more than 2-3 days on just that 'failed to install package form api.nuget.org'...
I check firewalls, proxy, os/visual studio setting, osma config files, .nuget files, reinstall/update nuget pakage installer, install packages manually... did every possible thing but no luck.

anyone, please?

**Comment by x0axz** [comment]
Error Log:
https://www.dropbox.com/sh/n1bsskno1gcv8v0/AAC_XR8qepgphI6D_GU_JE9ea?dl=0

**Comment by x0axz** [comment]
Is there any possiblity that we create docker image of OSMA (on a pc which runs it properly) and then run it on my pc (which can't run it)?
