### ISSUE TITLE
Project builds but can't really tell where to go from there.

### ISSUE THREAD

**Issue by daidoji** [mattrglobal/osma#7]
Project builds in VS 2019 but don't really know where to go from there.  Might be because I'm not a VS user.

**Comment by tplooker** [comment]
@daidoji are you able to deploy and run the app?

**Comment by tplooker** [comment]
@daidoji, which project do you have selected to build in visual studio, make sure you have one of the run time projects selected I.e the .Android or .iOS project.

**Comment by tplooker** [comment]
@daidoji I am going to close this issue as I have updated the readme which should provide some further clarity.

**Comment by daidoji** [comment]
Thanks @tplooker !  I'll try again.
